# -*- coding: utf-8 -*-
#"""dataCapture.ipynb
#
#Automatically generated by Colaboratory.
#
#Original file is located at
#    https://colab.research.google.com/drive/1rvuBbCet39g9QTi_8GA1llw2EBKb-noW
#"""

import os
import time

import cv2
import numpy as np
import pyrealsense2.pyrealsense2 as rs

#from realsense_depth import *




capName = ["Open","Closed","Radial5"] #Create these directories within the DIR path
DIR = "C:/Users/15184/Documents/Clarkson_Docs/CS670/dataCollectionTest" #CHANGE FOR LOCAL SYSTEM
pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.color, 640, 480, rs.format.bgr8, 30)
config.enable_stream(rs.stream.depth, 640, 480, rs.format.z16, 30)
#config.enable_record_to_file('test.bag')
align = rs.align(rs.stream.color)
pipeline.start(config)
frames = pipeline.wait_for_frames()
frames = align.process(frames)
color_frame = frames.get_color_frame()
depth_frame = frames.get_depth_frame()
color_image = color_frame.get_data()
depth_image = depth_frame.get_data()

os.chdir(DIR)
start = time.time()
countBin = 0
countR = 0

while(True):
    frames = pipeline.wait_for_frames()
    frames = align.process(frames)
    color_frame = frames.get_color_frame()
    depth_frame = frames.get_depth_frame()
    color_image = np.asanyarray(color_frame.get_data())
    depth_image = np.asanyarray(depth_frame.get_data())
    #ret, depth_frame, frame = dc.get_frame()
    cv2.imshow('frame', color_image)
    
    time_took = round((time.time() - start))
    #print(time_took)
    if time_took == 1:
        print("Radial Data Capture starting in 5 seconds")
    if time_took == 3:
        print("3")
    elif time_took == 4:
        print("2")
    elif time_took == 5:
        print("1")
    elif time_took > 5 and time_took < 30:
        
        fcount = "{:05n}".format(countR)
        imgName1 = "Radial" + fcount + '.png'
        imgName2 = "Depth" + fcount + '.png'
        countR += 1
        filename = os.path.join(DIR,capName[2])
        filename1 = os.path.join(filename,imgName1)
        filename2 = os.path.join(filename,imgName2)
        cv2.imwrite(filename1,color_image)
        depth_image.astype(np.uint16)
        #print(depth_image.dtype)
        #print(depth_image.shape)
        cv2.imwrite(filename2,depth_image)
        print(depth_image)
        print(f'Capturing Radial Image {countR}')    
        countR += 1
    elif time_took == 30:
        print("All Done, Please let next person get ready")
    elif time_took == 40:
        print("Restarting Now")
        start = time.time()
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
